### PR TITLE
Apply button in sound menu

### PR DESCRIPTION
**Pull request by Bishop-333**

### CODE REVIEW

**Comment by The-Gig** [comment]
Note: this is a follow-up https://github.com/OpenArena/gamecode/pull/200

**Comment by NeonKnightOA** [comment]
Neat! Can you produce a test .pk3 file so we can test it? :)

**Comment by Bishop-333** [comment]
> Neat! Can you produce a test .pk3 file so we can test it? :)

Of course here is it : 
[z_apply_button.pk3.zip](https://github.com/OpenArena/gamecode/files/14728965/z_apply_button.pk3.zip)

**Comment by NeonKnightOA** [comment]
Excellent! I'll give it a try the next week.

**Comment by NeonKnightOA** [comment]
I'm committing this one.

**Pull request merged**
