### PR TITLE
Replacement of direct array length calls by GT_MAX_GAME_TYPE constant call.

### PR DESCRIPTION
**Pull request by NeonKnightOA**

### CODE REVIEW

**Comment by sago007** [comment]
I find ARRAY_LEN a lot safer. I can instantly see that the next line does not cause undefined behaviour.

**Comment by NeonKnightOA** [comment]
So basically, the desired is the inverse: reverting GT_MAX_GAME_TYPE to the array length comparison?

**Comment by sago007** [comment]
> So basically, the desired is the inverse: reverting GT_MAX_GAME_TYPE to the array length comparison?
Only in cases where the check is used to validate array bonds. I would not use it anywhere else.

**Comment by NeonKnightOA** [comment]
Indeed.

**Pull request closed without merging**
