### PR TITLE
Frag message output with icons

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by The-Gig** [comment]
Just adding a link to the previous discussion on the topic:
https://github.com/OpenArena/gamecode/issues/8

**Comment by The-Gig** [comment]
Excuse me Idrone, you did not answer to a question I did here:
https://github.com/OpenArena/gamecode/issues/8#issuecomment-261703510

PS: You already know, I don't see any reason for hiding the attacker name, in case of indirect kill.

PPS: just asking for curiosity... why does the "case MOD_BFG:" section is completely empty? Because so it automatically takes the same settings as "case MOD_BFG_SPLASH" which is right under it? You know I'm not good with C...

**Comment by The-Gig** [comment]
Another thing: when someone is killed by a teammate, should't the iconographic version mention this, too? Like "x <skull icon> y (TEAMMATE)"...

**Comment by ldrone** [comment]
> PPS: just asking for curiosity... why does the "case MOD_BFG:" section is completely empty? Because so it automatically takes the same settings as "case MOD_BFG_SPLASH" which is right under it? You know I'm not good with C...

It "falls through" to the next case since there is no `break;` statement, which would exit the switch and resume after it. So the compiler continues to read the next lines of  `case MOD_BFG_SPLASH` until the next `break;` is encountered.

**Comment by The-Gig** [comment]
About the bfg question... so it's like I guessed. Thank you!

**Comment by sago007** [comment]
Ok, I have checked it out and also tryed playing it. Looks good. A bit hard to read on my screen but I could not read the console either, so it does not matter.

Regarding the code:
Your code is indented with spaces while most of the code is indented with tabs. I must admit that I have done the same at some point. Github just makes it much more obvious. I am not taking side in the spaces vs tab argumentation but it should be the same in all of the code. 

Also something like this:
```
 Q_strncpyz(lastFrag->targetName, targetName, 32);
```
The "32" should either be replaced by a "#define MAX_FRAG_NAME_LENGTH" or a "sizeof".

```
static int fadeTime = 7000;
```
should properly be
```
const int fadeTime = 7000;
```

I would greatly prefer curly brackets here:
```
if (cgs.fragMsg[i].teamFrag)
            CG_DrawStringExt(x + x_offset, y + (i * TINYCHAR_HEIGHT),
                  "(^1TEAMMATE^7)", hcolor, qfalse, qfalse,
                  TINYCHAR_WIDTH, TINYCHAR_HEIGHT, 0);
```
While it is only 1 logical line it is 3 physical lines and I would mark it. You also used curly brackets other places where the if content was more than 1 physical line.

Also
```
            if (ent->generic1) lastFrag->teamFrag = qtrue;
            else lastFrag->teamFrag = qfalse;
```
could be
```
            if (ent->generic1) {
                lastFrag->teamFrag = qtrue;
            }
            else {
                lastFrag->teamFrag = qfalse;
            }
```
or maybe just
```
lastFrag->teamFrag = ent->generic1;
```

Aside from that the code looked solid. 

Perhaps the commits should be squashed before merging. While it is easy enough to read all the commits as one in this pull request it might be harder in the commit history.

**Comment by ldrone** [comment]
I changed the cg_kickScale to show 1.0 as Gig suggested in #9. Should I leave that here since it's a minor change or else how would I go to make that a separate commit?

**Comment by sago007** [comment]
Doesn't matter. Just let it be in this.

**Comment by ldrone** [comment]
Replaced spaces with tabs. Currently in my editor, it's hard to see how the tabs between words will look on github.

**Comment by sago007** [comment]
Looks good to me!

**Pull request merged**
