### PR TITLE
New cvar for Harvester: g_harvesterFromBodies.

### PR DESCRIPTION
**Pull request by NeonKnightOA**
This cvar allows Harvester to work in a similar way to Unreal Tournament 3's Greed mode: it eliminates the neutral obelisk and makes the skulls appear from the fallen players' bodies instead.

Only one known issue, and is that the neutral obelisk, in spite of the checks, is still drawn in the map.

### CODE REVIEW

**Comment by sago007** [comment]
You might want to keep the neutral obelisk in case of a skull spawning in a nodrop zone. A skull dropped in a nodrop zone should be spawned at the neutral obelisk or the team obelisk furthest away from the target if the neutral obelisk is unavailable.

**Comment by NeonKnightOA** [comment]
An alternative path could be that in case of falling to the nodrop zone, the skull doesn't spawn. I'll see about that.

**Comment by NeonKnightOA** [comment]
Code updated. The cvar was also renamed so Gig doesn't complain.

**Comment by NeonKnightOA** [comment]
Since this was added, it's only appropriate to close the PR and delete the branch.

**Pull request closed without merging**
