### PR TITLE
Unifying format criteria for cvars in every module.

### PR DESCRIPTION
**Pull request by NeonKnightOA**
Tabs and extra spaces are replaced by a single space between words. Some cvars were moved to main. Some missing cvars were added to ui_local.h.

### CODE REVIEW

**Comment by sago007** [comment]
It looks good but there are some inconsistency:
oa_pull_57_tabs
Tabs are still used for non-indentation purposes in some of the modified code.

**Comment by NeonKnightOA** [comment]
Some cases have escaped to me, then. I'll fix them today if I can.

**Comment by NeonKnightOA** [comment]
Are we sure those weren't existing spaces? A quick search using SciTE returned no results upon **extern\tvmCvar_t\t**, **extern vmCvar_t\t**, and **vmCvar_t\t**.

**Comment by sago007** [comment]
It was just me that misinterpreted the Github page. I did not have access to a computer to validate myself. I got that now.

**Pull request merged**
