### PR TITLE
[Testing required] Domination AI improvements

### PR DESCRIPTION
**Pull request by NeonKnightOA**
I took a look at the AI gamecode in order to see how can I improve bot support for OA's newer gamemodes. This specific PR focuses on Double Domination and Domination.

**[Test PK3](https://www.dropbox.com/s/mkgjyglgqyldi7q/z_oax-classicui-domsupport.pk3?dl=0). _Updated March 20, 2022._ Also requesting code review as I'm sure there are still some rough edges to polish.. - [Related forum thread](http://openarena.ws/board/index.php?topic=5458.0).**

**What needs to be tested?**

* Botmatches in Domination.
* How bots react to orders.
* If the bots do indeed go to pick the DOM points.
* Anything else that I'm missing.

**Additional notes**

- Currently the bots in Domination are set to pick a random point and hold onto it.
- As for their behavior, **the bots will pick a random point (if it falls inside of both established map and gametype limits -WIP-) and act upon it.** If the point is already taken, they can choose to hold onto that point, or go chase after another empty/enemy-controlled point. If all the points are taken, the bot will pick one at random and hold onto it. **The point of interest changes every time they're given an order or enter the game.**
* **Absence of control points will make the bots to roam through the map**. Also behavior accounts for the presence of a team leader, last goal, aggression and preference.

**To-Do**

* **Bots take a lot of time to reach the points and often get distracted in fights.** They should go straight to the CP.
* A feature I'd like to add, yet I haven't thought about how to put it in the code: **if an info_camp entity is linked to a DOM point or a flag, the bot should use it as a defense point**. Obviously the "angles" key should be pointing to the direction the bot should cover while defending.
* While checking ai_team.c, I figured out that bots have different team formations for aggressive and passive modes. I'd like to implement those as well in these modes.
* **Additional checks for gametype limits.**

### CODE REVIEW

**Comment by NeonKnightOA** [comment]
[Last testing pk3 until next time](https://cdn.discordapp.com/attachments/405518544382590987/673264685541228584/z_oax_v2.pk3)

I think I've made the orders work this time. Both the generic "Attack" and "Defend" orders will trigger "Hold point A" and "Hold point B" in DD, and both of them trigger "Hold a random point" in regular Domination.

**Comment by NeonKnightOA** [comment]
[New version to test.](https://cdn.discordapp.com/attachments/405518544382590987/674674084415668253/z_oax_v2.pk3)

Unifying criteria in functions that use the CP picking function. Also accounting for no CPs in the picking function. What does this mean? **In DOM games taking place in maps with no CPs, ideally, they should be happy just roaming the map and not causing crashes.**

**Comment by NeonKnightOA** [comment]
**[New test pk3](https://cdn.discordapp.com/attachments/405518544382590987/675479934239506442/z_oax_v2.pk3)**

This time only DD changes:
- Voice speech support for DD (only available through MP and no proper sounds)
- Team formations for passive/aggressive strategies when a team only holds one point. In a passive strategy, the bots will focus on fortifying the already taken point, while in an aggressive strategy, the bots will focus on taking the uncontrolled point.

**Comment by NeonKnightOA** [comment]
If I can't today, tomorrow I'll upload test pk3 for this and #106 .

**Comment by NeonKnightOA** [comment]
**[New test PK3](https://cdn.discordapp.com/attachments/405518544382590987/676472027862925361/z_oax_v2.pk3). Only DOM changes. DD ones are located in #106 .**

**Comment by The-Gig** [comment]
Done some testing with a couple of bots. All in the same team (no opponents).
- They seem to be camping a lot (especially Angelyss)... but not near to flags.
- They sometime say they are going to capture and keep a point, but often they don't actually do it. -- Also, maybe the most automatic behavior with no orders should be to roam between the various points, instead of sticking to one specific point and leaving all the others to the enemies? Just wondering...
- They do not "reply" if I say them to roam, however they accomplish (BTW, is seems also in 0.8.8 in TDM mode, they don't say a word when you say them to roam. Strange, I thought they did...)
- Sometimes they reply to my "report" command, sometimes not.

**Comment by The-Gig** [comment]
Some more testing, me against one bot... Although still not super efficient, Sarge seems to be more interested than Angelyss into capturing Dom points. A couple of times the game *crashed*.

**Comment by NeonKnightOA** [comment]
Testing PK3 updated.

**Comment by NeonKnightOA** [comment]
Closing for the moment as this is still a WIP.

**Pull request closed without merging**
