### PR TITLE
Domination-specific fixes for botplay.

### PR DESCRIPTION
**Pull request by NeonKnightOA**
To-Do: Fix the ordering.

### CODE REVIEW

**Comment by sago007** [comment]
Crashes for me when launching a game on oa_shouse. The map does not have any domination points but the game should not have crashed. I notice that you divide by level.domination_points_count, however the game still crashed after I removed that, so there must be something else.

**Comment by NeonKnightOA** [comment]
Weird, the 0.8.8 version of the map should have three points. I need to check this.

**Comment by The-Gig** [comment]
_IIRC_ (!!!) the map was listed for domination in arenas file, but it didn't actually show any domination point...

**Comment by sago007** [comment]
It does not really matter for this issue. The game should not break on a map as long as the map contains a spawn point.

**Comment by NeonKnightOA** [comment]
It seems something that should be solved with a sanity check.
Can't check right now. But I guess that checking if the amount of domination points is below 1 should suffice to solve any problem regarding crashes.

**Comment by NeonKnightOA** [comment]
I've added a sanity check which makes the bots to just roam in case of no points, as well as removed an unnecessary function.

**Comment by NeonKnightOA** [comment]
Closing for the moment. I think it will be better to analyze how the AI code works and what can be done before any support can be introduced.

**Pull request closed without merging**
