### PR TITLE
team status bar fix

### PR DESCRIPTION
**Pull request by EddieBrrrock**
small fix to shift the colored bar to prevent it from overwriting the score

### CODE REVIEW

**Comment by EddieBrrrock** [comment]
Before :
shot0002
After :
shot0001

**Comment by EddieBrrrock** [comment]
look at the score at the bottom right

**Comment by KuehnhammerTobias** [comment]
Did you test this with cg_drawteamoverlay right/bottom?

**Comment by The-Gig** [comment]
Tomorrow the change should appear in a new nightly build here <https://files.poulsander.com/~poul19/public_files/oa/dev088/gamecode_nightly/>, but I will not have access to a PC for a few days..

**Comment by EddieBrrrock** [comment]
In fact @KuehnhammerTobias you was right, it need more changes. Here's the needed changes to work well with the cg_drawteamoverlay I forget to update the pull request since its 1 year ago : https://github.com/EddieBrrrock/gamecode/commit/8b9c5593b4e955702890ead07d6bc50e554716ef
@The-Gig idk if its better to do the fix before doing the release

**Comment by EddieBrrrock** [comment]
https://github.com/OpenArena/gamecode/pull/172

**Pull request merged**
