### PR TITLE
Frag msg v2

### PR DESCRIPTION
**Pull request by ldrone**

### CODE REVIEW

**Comment by ldrone** [comment]
This code for testing empty string as sago007 suggested, isn't working for some reason:
```
if (fi.attackerName != '\0')
```

**Comment by sago007** [comment]
> if (fi.attackerName != '\0')

I was thinking more like this:
`if (fi.attackerName[0] != '\0')`
We test if the first char is the end.
This should properly have a function or a macro.

**Comment by ldrone** [comment]
My mistake.

**Comment by sago007** [comment]
Looks good to me

**Comment by The-Gig** [comment]
For completeness, considering this commit reorganized the options:

**cg_obituaryoutput**:
- 0: no obituary output
- 1: console (text) only ("classic" behavior)
- 2: hud (text) only
- 3: hud (icons) only (new default)
- 4: hud (icons) + console (text)

**Pull request merged**
