### PR TITLE
New cvars for Double Domination: g_ddRespawnDelay and g_ddCaptureTime

### PR DESCRIPTION
**Pull request by NeonKnightOA**
g_ddCaptureTime controls the amount of seconds required to score a point if both points are held.
g_ddRespawnDelay controls the amount of seconds between a capture and the start of a new round.

Both cvars are equivalent to UT200X's options for Double Domination.

### CODE REVIEW

**Comment by sago007** [comment]
Looks good to me. I'll cherry pick https://github.com/OpenArena/gamecode/pull/31/commits/48328735234480da7204885b8d5557aed5b70e74 directly though.

**Comment by The-Gig** [comment]
Not sure if the better names for those cvars should be like g_dd_captureTime or like g_ddCaptureTime (without the second underscore)... simply because the second way would follow the existing g_obelisk* options.
I'm not sure about what's the better choice.

**Comment by NeonKnightOA** [comment]
Code updated. The cvars were also renamed.

**Comment by NeonKnightOA** [comment]
I'm having a problem.

Here's a piece of code from `g_main.c`:

```
void CheckDoubleDomination( void )
{
    if ( level.numPlayingClients < 1 ) {
        return;
    }
 
    if ( level.warmupTime != 0) {
        if( ((level.pointStatusA == TEAM_BLUE && level.pointStatusB == TEAM_BLUE) ||
                (level.pointStatusA == TEAM_RED && level.pointStatusB == TEAM_RED)) &&
                level.ddTimeTaken + g_ddCaptureTime.integer*1000 <= level.time ) {
            Team_RemoveDoubleDominationPoints();
            level.roundStartTime = level.time + g_ddRespawnDelay.integer*1000;
            SendScoreboardMessageToAllClients();
        }
        return;
    }
 
    if(g_gametype.integer != GT_DOUBLE_D)
        return;
 
    //Don't score if we are in intermission. Both points might have been taken when we went into intermission
    if(level.intermissiontime)
        return;
 
    //Red scores
    if(level.pointStatusA == TEAM_RED && level.pointStatusB == TEAM_RED &&
        level.ddTimeTaken + g_ddCaptureTime.integer*1000 <= level.time) {
        trap_SendServerCommand( -1, "print \"Red team scores!\n\"");
        AddTeamScore(level.intermission_origin,TEAM_RED,1);
        G_LogPrintf( "DD: %i %i %i: %s scores!\n", -1, TEAM_RED, 2, TeamName(TEAM_RED) );
        Team_ForceGesture(TEAM_RED);
        Team_DD_bonusAtPoints(TEAM_RED);
        Team_RemoveDoubleDominationPoints();
        level.roundStartTime = level.time + g_ddRespawnDelay.integer*1000;
    }
 
    //Blue scores
    if(level.pointStatusA == TEAM_BLUE && level.pointStatusB == TEAM_BLUE &&
        level.ddTimeTaken + g_ddCaptureTime.integer*1000 <= level.time) {
        trap_SendServerCommand( -1, "print \"Blue team scores!\n\"");
        AddTeamScore(level.intermission_origin,TEAM_BLUE,1);
        G_LogPrintf( "DD: %i %i %i: %s scores!\n", -1, TEAM_BLUE, 2, TeamName(TEAM_BLUE) );
        Team_ForceGesture(TEAM_BLUE);
        Team_DD_bonusAtPoints(TEAM_BLUE);
        Team_RemoveDoubleDominationPoints();
        level.roundStartTime = level.time + g_ddRespawnDelay.integer*1000;
    }
   
    /* Neon_Knight: Time between a capture and the point respawn moved here */
    if(level.pointStatusA == TEAM_NONE && level.pointStatusB == TEAM_NONE &&
        level.time<level.roundStartTime) {
        trap_SendServerCommand( -1, va("print \"Remaining time: %i seconds...\n\"", (level.roundStartTime-level.time)/1000));
        SendScoreboardMessageToAllClients();
        CalculateRanks();
    }
    /* /Neon_Knight */
   
    if((level.pointStatusA == TEAM_NONE || level.pointStatusB == TEAM_NONE) &&
        level.time>level.roundStartTime) {
        trap_SendServerCommand( -1, "print \"A new round has started!\n\"");
        G_LogPrintf( "\"A new round has started!\"" );
        Team_SpawnDoubleDominationPoints();
        SendScoreboardMessageToAllClients();
    }
}
```

The piece which starts with the comment _"Time between a capture and the point respawn moved here"_ repeats the message _"Next round starts in x seconds..."_ to the point of flooding the console. I suppose the message shouldn't go there but in a function in cgame.

And speaking of cgame, I can't get the game module to communicate the limits to the cgame module.

**Pull request closed without merging**
