### PR TITLE
[WIP] Announcer stuff

### PR DESCRIPTION
**Pull request by NeonKnightOA**
**[Test pk3](https://www.dropbox.com/s/w3238ybwdfu8yl1/z_oax-classicui-newannouncer.pk3?dl=0)** _(Updated March 20, 2020, 22:17 GMT-3)_ Also attaching [this other pk3](https://www.dropbox.com/s/u7ctwjz26wf6go4/z_announcersoundsfortesting.pk3?dl=0) _(Updated March 20, 2020, 22:17 GMT-3)_ which contains all new announcer lines, including the new ones introduced in this test pk3.

Overview: Announcer sound routes were separated from the code into a header file. This header file can be put into a pk3 with custom announcer sound routes, which can be replaced as well just by regular sounds in case someone finds the announcer annoying.

The announcer pk3 also contains recorded new announcer lines for game spectating. These are the new announcements:

* **Numbers from 4 to 10.** (Used mostly in countdowns)
* _**"Three/Two minutes left"**_
* _**"Red/Blue team has the Blue/Red flag"**_ (For CTF/eCTF matches, spectator only)
* _**"Red/Blue team has the flag"**_ (1FCTF matches, spectator only)
* _**"Red/Blue base is under attack"**_ (Overload matches, spectator only, **requires testing**)
* _**"Lead switch"**_ (FFA and Possession matches, spectator only, **not fully implemented yet**)

Also, two new cvars:

* **cg_announcePowerups**: a bitflag which can take the following values; the idea being that setting the cvar to 0 replaces all announcer lines with regular sounds (may come in handy for people who don't want to hear too many announcements):
  * 1) Announces powerups once taken
  * 2) Announces holdables once taken
  * 4) Announces runes once taken
* **cg_customAnnouncer**: allows the use of the aforementioned custom announcers. Setting it to 0 makes it to fall back to default announcer sounds. **(Not fully implemented due to OA having a mix of announced powerups and item pickup sounds)**

Possible ideas:

* **cg_announcePowerupRespawn**: Set to 0, triggers an announcer line whenever a powerup respawned (something that many AFPS seem to be including these days, OFC can be disabled). Also a bitflag, so it can also announce holdables and runes. (In order to avoid confusion, cg_announcePowerups could be renamed to cg_announcePowerupPickups)
* **Missing announcements:** I haven't figured out yet where should I code in order to add these. There are audio lines recorded in order to test.
  - _**"New round in...**"_ (for Overload, Elimination, CTF Elimination, Last Man Standing and Double Domination, played after a team scores a point)
  - _**"Blue/Red team dominates!"**_ (for Double Domination, played instantly after a team takes both points, like UT2004)

LET THE NITPICK BEGIN!

### CODE REVIEW

**Comment by The-Gig** [comment]
I would like to know some players' opinions about timelimit warnings for three and two minutes, thinking about usefulness/annoyance ratio...
Some players around here? If you don't have a Github account, you can post your considerations on OpenArena Discord server.

**Comment by NeonKnightOA** [comment]
In that case, announcements can be controlled via a cvar. I don't recall if there's already a cg_enableAnnouncer (0 should disable it, 1 should enable it). If it exists, it could be extended with other values that enable/disable additional announcements. Then again, the announcer lines could be replaced with just regular sounds or silence.

**Comment by NeonKnightOA** [comment]
Commit OpenArena/gamecode@2dd165b added spectator-specific lines for CTF, eCTF, 1FCTF and Overload. This should also solve the problem with Harvester. I still haven't figured out how to add announcer lines for Double Domination ("Blue/Red team dominates"), as well as "New round in..." for round-based gametypes and Double Domination (Overload would also benefit from this).

**Comment by NeonKnightOA** [comment]
**Test PK3 available!** Invoking @The-Gig .

**Comment by NeonKnightOA** [comment]
Test PK3 was quickly rendered obsolete. :/

However I've FINALLY made spectator-specific announcer lines work in CTF, 1FCTF and eCTF! Only Overload needs testing because I've found out a bug with the bots in this gamemode.

**Comment by NeonKnightOA** [comment]
Writing an idea for later: **cg_announcerFlags**: enables/disables specific announcements as required. Can even be set to 0 in order to completely disable it.

**Comment by NeonKnightOA** [comment]
Updated testing PK3 and testing announcer.

**Comment by NeonKnightOA** [comment]
Closing for the moment.

**Pull request closed without merging**
