### PR TITLE
Fix: cg_weaponBarStyle with value outside of range now displays default weapon bar.

### PR DESCRIPTION
**Pull request by NeonKnightOA**
Previously it would hide the weapon bar completely.

### CODE REVIEW

**Comment by The-Gig** [comment]
I think the difference between 5 and 7 is that with 7 the background slowly changes from blue to red as your ammo goes down.

Also, I don't know if to use -1 or 8 for "no weapon bar"... What do you think existing users would expect more?

**Comment by The-Gig** [comment]
See also: https://github.com/OpenArena/gamecode/issues/143

**Comment by sago007** [comment]
I like that the weapon bars are now described by comments.

**Comment by NeonKnightOA** [comment]
I hope the comments I wrote were accurate, at least.

**Comment by The-Gig** [comment]
Uhm... Maybe you forgot to update the comments of those that at first look seem the same,  but with the background that changes slowly? See the second post of this discussion.

**Pull request merged**
