### PR TITLE
Widescreen fix

### PR DESCRIPTION
**Pull request by Bishop-333**
Make the leilei widescreen fix cvar dependant to avoid code deleting and fix hud position :

**BEFORE :** 
Capture d’écran 2024-03-15 à 22 46 51
Capture d’écran 2024-03-15 à 22 59 35

**AFTER :** 
Capture d’écran 2024-03-15 à 22 49 35
Capture d’écran 2024-03-15 à 22 59 20

It caused some element to draw over others like the cg_drawteamhud drawing over the scores

### CODE REVIEW

**Comment by Bishop-333** [comment]
PS : fps change is not related and cg_leiWidescreen was unused so setting it to 0 will have no other impact

**Comment by NeonKnightOA** [comment]
Noted and committed.

**Comment by leilei-** [comment]
fix the other elements instead.

**Comment by Bishop-333** [comment]
I didnt mean your code deleting improvement but avoid the deletion of your code, but ok ill try get around and find a solution

**Pull request merged**
